const fs = require('fs');
const path = 'd:/MY WORK FLOW/EMYOMS/admin.html';
let content = fs.readFileSync(path, 'utf8');
const lines = content.split('\n');

// We know the file is good up to line 3008 (Row 2 of Expense Modal ends at 3008)
// Let's find a safe line to cut at.
// Looking at the view_file output:
// 3008:                 </div>
// 3009: 
// 3010:     <!-- Datalists for Auto-population -->

const start = lines.slice(0, 3009).join('\n');

const rest = `
                <!-- Row 3: Amount, Method, Ref -->
                <div style="display: grid; grid-template-columns: 1.5fr 1fr 1fr; gap: 1.5rem; margin-bottom: 1.5rem;">
                    <div class="form-group">
                        <label style="font-size:0.7rem; font-weight:800; color:#ef4444; margin-bottom:8px; display:block;">AMOUNT (₹)</label>
                        <input type="number" id="exp-amount" required step="0.01" placeholder="0.00" style="font-size:1.6rem; font-weight:900; color:#ef4444; background:rgba(239,68,68,0.05); border:2px solid #ef4444; border-radius:16px; padding:12px; text-align:center;">
                    </div>
                    <div class="form-group">
                        <label style="font-size:0.7rem; font-weight:800; margin-bottom:8px; display:block;">PAYMENT METHOD</label>
                        <select id="exp-method" style="padding:12px; background:rgba(0,0,0,0.4); border:2px solid var(--glass-border); border-radius:12px;">
                            <option value="Cash">Cash</option>
                            <option value="Bank Transfer">Bank Transfer</option>
                            <option value="UPI">UPI / GPay</option>
                            <option value="Cheque">Cheque</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label style="font-size:0.7rem; font-weight:800; margin-bottom:8px; display:block;">REFERENCE NO</label>
                        <input type="text" id="exp-ref" placeholder="Receipt / TxnID" style="padding:12px; background:rgba(0,0,0,0.4); border:2px solid var(--glass-border); border-radius:12px;">
                    </div>
                </div>

                <!-- Notes -->
                <div class="form-group" style="margin-bottom:2rem;">
                    <label style="font-size:0.7rem; font-weight:800; margin-bottom:8px; display:block;">NOTES (Optional)</label>
                    <textarea id="exp-notes" rows="2" placeholder="Additional details..." style="width:100%; padding:12px; background:rgba(0,0,0,0.4); border:2px solid var(--glass-border); border-radius:12px; color:#fff; resize:vertical;"></textarea>
                </div>

                <div style="display:flex; justify-content:flex-end; gap:1.5rem; border-top:1px solid var(--glass-border); padding-top:1.5rem;">
                    <button type="button" class="btn btn-ghost" onclick="document.getElementById('expenseModal').classList.add('hidden')">CANCEL</button>
                    <button type="submit" class="btn btn-primary" style="background: linear-gradient(135deg,#ef4444,#f97316); border:none; padding:12px 40px; font-weight:900;">💸 POST EXPENSE</button>
                </div>
            </form>
        </div>
    </div>

    <!-- PICKER (Floating Month-Year Grid) -->
    <div id="monthYearPickerModal" class="hidden" style="position: absolute; z-index: 11000; pointer-events: auto;">
        <div class="glass-card" style="width: 280px; padding: 1rem; border-top: 3px solid var(--primary); text-align: center; border-radius: 16px; box-shadow: 0 20px 40px rgba(0,0,0,0.6); border: 1px solid rgba(255,255,255,0.1); background: rgba(15, 23, 42, 0.98); backdrop-filter: blur(20px);">
            <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 1rem; background: rgba(255,255,255,0.03); padding: 8px; border-radius: 10px;">
                <button type="button" class="btn btn-ghost" style="padding: 2px 8px; font-size: 1rem; color: var(--primary);" onclick="event.stopPropagation(); changePickerYear(-1)">❮</button>
                <div id="picker-year-display" style="font-size: 1.1rem; font-weight: 800; color: #fff; letter-spacing: 1px;">2024</div>
                <button type="button" class="btn btn-ghost" style="padding: 2px 8px; font-size: 1rem; color: var(--primary);" onclick="event.stopPropagation(); changePickerYear(1)">❯</button>
            </div>
            
            <div id="picker-month-grid" style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; margin-bottom: 1rem;">
                <!-- Generated by JS -->
            </div>
            
            <div style="display: flex; gap: 8px;">
                <button type="button" class="btn btn-ghost" style="flex: 1; font-weight: 700; font-size: 0.7rem; padding: 5px;" onclick="closeMonthYearPicker()">CLOSE</button>
            </div>
        </div>
    </div>

    <!-- Datalists for Auto-population -->
    <datalist id="category-list"></datalist>
    <datalist id="group-list"></datalist>
    <datalist id="hsn-list"></datalist>
    <datalist id="gst-rate-list"></datalist>
    <datalist id="stockist-list"></datalist>
    <datalist id="expense-head-list"></datalist>

    <script src="admin-script.js?v=2.8"></script>

    <audio id="bgMusic" loop preload="auto"></audio>
</body>
</html>
`;

fs.writeFileSync(path, start + '\n' + rest);
console.log('Successfully repaired admin.html');
