module.exports = (sequelize, DataTypes) => {
    return sequelize.define('Company', {
        id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
        name: { type: DataTypes.STRING, defaultValue: "EMYRIS BIOLIFESCIENCES" },
        address: { type: DataTypes.TEXT, defaultValue: "" },
        websites: { type: DataTypes.ARRAY(DataTypes.STRING), defaultValue: [] },
        phones: { type: DataTypes.ARRAY(DataTypes.STRING), defaultValue: [] },
        tollFree: { type: DataTypes.STRING, defaultValue: "" },
        emails: { type: DataTypes.ARRAY(DataTypes.STRING), defaultValue: [] },
        superDistributorEmail: { type: DataTypes.STRING, defaultValue: "" },
        adminEmail: { type: DataTypes.STRING, defaultValue: "" },
        gstRate: { type: DataTypes.FLOAT, defaultValue: 12 },
        state: { type: DataTypes.STRING, defaultValue: "TELANGANA" },
        gstNo: { type: DataTypes.STRING, defaultValue: "" },
        panNo: { type: DataTypes.STRING, defaultValue: "" },
        dlNo: { type: DataTypes.STRING, defaultValue: "" },
        fssaiNo: { type: DataTypes.STRING, defaultValue: "" },
        bankDetails: { type: DataTypes.TEXT, defaultValue: "" },
        bankAccountNo: { type: DataTypes.STRING, defaultValue: "" },
        bankIfsc: { type: DataTypes.STRING, defaultValue: "" },
        upiId: { type: DataTypes.STRING, defaultValue: "" },
        paymentDueDays: { type: DataTypes.INTEGER, defaultValue: 21 },
        defaultPlaceOfSupply: { type: DataTypes.STRING, defaultValue: "" },
        termsConditions: { type: DataTypes.TEXT, defaultValue: "" },
        invoiceTerms: { type: DataTypes.TEXT, defaultValue: "" },
        cnTerms: { type: DataTypes.TEXT, defaultValue: "" },
        dnTerms: { type: DataTypes.TEXT, defaultValue: "" },
        invoiceBankVisible: { type: DataTypes.BOOLEAN, defaultValue: true },
        cnBankVisible: { type: DataTypes.BOOLEAN, defaultValue: false },
        dnBankVisible: { type: DataTypes.BOOLEAN, defaultValue: false },
        signatureImage: { type: DataTypes.TEXT, defaultValue: "" },
        logoImage: { type: DataTypes.TEXT, defaultValue: "" },
        scrollingMessage: { type: DataTypes.JSONB, defaultValue: {} },
        invoiceStyle: { type: DataTypes.STRING, defaultValue: 'classic' },
        documentCounters: { type: DataTypes.JSONB, defaultValue: {} },
        musicUrl: { type: DataTypes.STRING(1024), defaultValue: "" },
        videoUrl: { type: DataTypes.STRING(1024), defaultValue: "" },
        musicVolume: { type: DataTypes.FLOAT, defaultValue: 0.5 },
        referenceInvoiceUrl: { type: DataTypes.STRING(1024), defaultValue: "" }
    });
};
